const views = document.querySelectorAll('.view'); const nav = document.querySelectorAll('[data-view]');
const titleMap={command:['⌘','Command Center'],chat:['✦','Conversations'],tasks:['◈','Tasks & Runs'],browser:['◉','Browser'],intelligence:['⌁','Intelligence'],workflows:['↗','Workflows'],codelab:['›_','Code Lab'],mail:['✉','Mail'],connections:['⟐','Connections'],settings:['⚙','Settings'],about:['N3','N3K JV Identity']};
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.getElementById('viewIcon').textContent=titleMap[id][0];document.getElementById('viewTitle').textContent=titleMap[id][1];window.scrollTo({top:0,behavior:'smooth'});}
nav.forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
const toast=document.getElementById('toast'); function note(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function runCommand(text){if(!text.trim())return;showView('chat');const msgs=document.getElementById('messages');msgs.insertAdjacentHTML('beforeend',`<div class="message user">${text.replace(/[<>]/g,'')}</div>`);setTimeout(()=>{msgs.insertAdjacentHTML('beforeend',`<div class="message ai">I’m ready to help with that. I’ll keep this in context and ask before any sensitive or external action.</div>`);msgs.scrollTop=msgs.scrollHeight},480)}
document.getElementById('sendBtn').onclick=()=>{runCommand(document.getElementById('commandInput').value);document.getElementById('commandInput').value=''};document.getElementById('commandInput').addEventListener('keydown',e=>{if(e.key==='Enter'){document.getElementById('sendBtn').click()}});
document.getElementById('chatForm').addEventListener('submit',e=>{e.preventDefault();runCommand(document.getElementById('chatInput').value);document.getElementById('chatInput').value=''});
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{document.getElementById('commandInput').value=b.dataset.prompt;document.getElementById('commandInput').focus()});
const stage=document.getElementById('avatarStage'), state=document.getElementById('stateText');document.getElementById('micBtn').onclick=()=>{const on=!stage.classList.contains('listening');stage.className='avatar-stage'+(on?' listening':'');state.textContent=on?'LISTENING · SAY “N3K JV”':'READY TO ASSIST';note(on?'Voice input activated':'Voice input stopped')};
document.querySelectorAll('.action-btn,.browser-bar button,.new-chat,.confirm-row button').forEach(b=>b.addEventListener('click',()=>note('This action needs a connected Android service or your confirmation.')));
document.getElementById('menuBtn').onclick=()=>note('Navigation is available above in this mobile view.');
